"""
ScribbleNet - Streamlit Frontend
Web-based interface for handwritten word recognition.
"""

import io
import sys
import tempfile
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st
from PIL import Image

from utils.file_manager import load_config, resolve_path
from utils.logger import setup_logger


def init_session_state() -> None:
    """Initialize Streamlit session state variables."""
    if "engine" not in st.session_state:
        st.session_state.engine = None
    if "result" not in st.session_state:
        st.session_state.result = None
    if "preprocessed_steps" not in st.session_state:
        st.session_state.preprocessed_steps = None


@st.cache_resource
def load_engine():
    """Load the inference engine (cached)."""
    from backend.inference import ScribbleNetInference

    config = load_config()
    setup_logger(
        name="scribblenet",
        log_file=str(resolve_path(config["logging"]["file"])),
        level=config["logging"]["level"],
    )
    engine = ScribbleNetInference(config=config)
    return engine, config


def generate_txt(text: str) -> bytes:
    """Generate TXT file content."""
    return text.encode("utf-8")


def generate_pdf(text: str, confidence: float) -> bytes:
    """Generate PDF file with prediction results."""
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", "B", 20)
        pdf.cell(0, 15, "ScribbleNet - Recognition Result", ln=True, align="C")
        pdf.ln(10)
        pdf.set_font("Arial", "", 14)
        pdf.cell(0, 10, f"Predicted Text: {text}", ln=True)
        pdf.cell(0, 10, f"Confidence: {confidence * 100:.2f}%", ln=True)
        pdf.ln(10)
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 10, "Generated by ScribbleNet - Transformer-Based HTR System", ln=True)

        return bytes(pdf.output())
    except ImportError:
        return b"PDF generation requires fpdf2. Install with: pip install fpdf2"


def main() -> None:
    """Main Streamlit application."""
    st.set_page_config(
        page_title="ScribbleNet",
        page_icon="✍️",
        layout="wide",
    )

    init_session_state()

    # Header
    st.title("✍️ ScribbleNet")
    st.markdown(
        "**Transformer-Based Handwritten Word Recognition System**  \n"
        "Upload a handwritten word image and get AI-powered transcription."
    )
    st.divider()

    # Sidebar
    with st.sidebar:
        st.header("⚙️ Settings")
        apply_dip = st.checkbox("Apply DIP Preprocessing", value=True)
        show_steps = st.checkbox("Show Preprocessing Steps", value=False)
        num_beams = st.slider("Beam Width", min_value=1, max_value=10, value=4)
        st.divider()
        st.markdown("### About")
        st.markdown(
            "ScribbleNet uses the **TrOCR** transformer model "
            "fine-tuned for handwritten word recognition."
        )

    # Main content
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("📤 Upload Image")
        uploaded_file = st.file_uploader(
            "Choose a handwritten word image",
            type=["png", "jpg", "jpeg", "tif", "tiff", "bmp"],
        )

        if uploaded_file is not None:
            image = Image.open(uploaded_file).convert("RGB")
            st.image(image, caption="Uploaded Image", use_container_width=True)

            if st.button("🔍 Recognize Text", type="primary", use_container_width=True):
                with st.spinner("Loading model and processing..."):
                    try:
                        engine, config = load_engine()

                        # Show preprocessing steps if requested
                        if show_steps and apply_dip:
                            # Save to temp file for preprocessing pipeline
                            with tempfile.NamedTemporaryFile(
                                suffix=".png", delete=False
                            ) as tmp:
                                image.save(tmp.name)
                                from dip.preprocessing import preprocess_for_display
                                steps = preprocess_for_display(tmp.name)
                                st.session_state.preprocessed_steps = steps

                        # Run inference
                        result = engine.predict(
                            image,
                            apply_dip=False,  # Already PIL, skip file-based DIP
                            num_beams=num_beams,
                        )
                        st.session_state.result = result

                    except Exception as e:
                        st.error(f"Error: {str(e)}")

    with col2:
        st.subheader("📊 Results")

        if st.session_state.result is not None:
            result = st.session_state.result

            # Prediction display
            st.markdown("### Predicted Text")
            st.success(f"**{result['text']}**")

            # Confidence
            confidence = result["confidence"]
            st.markdown("### Confidence Score")
            st.progress(confidence)
            st.metric("Confidence", f"{confidence * 100:.2f}%")

            st.divider()

            # Download options
            st.markdown("### 📥 Download Results")
            dl_col1, dl_col2 = st.columns(2)

            with dl_col1:
                txt_content = generate_txt(
                    f"Predicted: {result['text']}\n"
                    f"Confidence: {confidence * 100:.2f}%"
                )
                st.download_button(
                    "Download TXT",
                    data=txt_content,
                    file_name="scribblenet_result.txt",
                    mime="text/plain",
                    use_container_width=True,
                )

            with dl_col2:
                pdf_content = generate_pdf(result["text"], confidence)
                st.download_button(
                    "Download PDF",
                    data=pdf_content,
                    file_name="scribblenet_result.pdf",
                    mime="application/pdf",
                    use_container_width=True,
                )
        else:
            st.info("Upload an image and click 'Recognize Text' to see results.")

    # Preprocessing steps display
    if st.session_state.preprocessed_steps is not None and show_steps:
        st.divider()
        st.subheader("🔬 Preprocessing Steps")
        steps = st.session_state.preprocessed_steps
        cols = st.columns(len(steps))
        for i, (step_name, step_img) in enumerate(steps.items()):
            with cols[i]:
                st.image(step_img, caption=step_name, use_container_width=True)

    # Footer
    st.divider()
    st.markdown(
        "<div style='text-align: center; color: gray;'>"
        "ScribbleNet v1.0 — Transformer-Based Handwritten Word Recognition"
        "</div>",
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
